// 04_recursive_macros.rs — Recursive macro_rules! for complex patterns
//
// Macro_rules! supports recursion: a macro can call itself in its expansion.
// This enables processing token streams of arbitrary length with complex structure.
//
// The key technique: macro calls itself with a smaller/further-processed token
// stream until a base case (non-recursive arm) is reached.

#![recursion_limit = "256"]

/// Compute factorial at compile time using a recursive macro.
/// Uses literal matching so recursion is bounded at compile time.
macro_rules! factorial {
    // Base cases for common values
    (0) => { 1 };
    (1) => { 1 };
    (2) => { 2 };
    (3) => { 6 };
    (4) => { 24 };
    (5) => { 120 };
    (6) => { 720 };
    // Recursive case: only for literal values
    ($n:literal) => {{
        $n * factorial!($n - 1)
    }};
}

/// Countdown using a runtime loop generated by the macro.
/// This avoids compile-time recursion issues entirely.
macro_rules! countdown_loop {
    ($n:expr) => {{
        let mut x = $n as i32;
        while x >= 0 {
            if x == 0 {
                println!("0...");
                println!("Liftoff!");
            } else {
                println!("{}...", x);
            }
            x -= 1;
        }
    }};
}

/// Recursive macro that builds a deeply nested tuple.
macro_rules! nest_tuple {
    // Base: single value
    ($x:expr) => { $x };
    // Recursive: ( $first, nest_tuple!(rest...) )
    ($first:expr, $($rest:expr),+) => {
        ($first, nest_tuple!($($rest),+))
    };
}

/// Peano arithmetic: represent numbers as recursive types via macros.
macro_rules! peano {
    (zero) => {
        ()
    };
    (succ $n:expr) => {
        ((), $n)
    };
}

/// Recursive macro that builds a string from repeated patterns.
/// Each repetition processes one token and recurses on the rest.
macro_rules! csv_string {
    // Base: one item
    ($x:expr) => { format!("{}", $x) };
    // Recursive: item, comma, recurse
    ($first:expr, $($rest:expr),+) => {
        format!("{}, {}", $first, csv_string!($($rest),+))
    };
}

/// Compute factorial at runtime using a recursive function generated by macro.
/// This avoids the compile-time recursion issue entirely.
macro_rules! factorial_runtime {
    ($n:expr) => {{
        fn fact(n: u64) -> u64 {
            if n <= 1 { 1 } else { n * fact(n - 1) }
        }
        fact($n)
    }};
}

fn main() {
    println!("=== Recursive Macros ===");

    // Factorial via literal matching (compile-time expansion)
    println!("5! = {} (literal pattern)", factorial!(5)); // 120
    println!("3! = {} (literal pattern)", factorial!(3)); // 6

    // Factorial via generated recursive function (runtime)
    println!("7! = {} (runtime fn)", factorial_runtime!(7)); // 5040

    // Countdown (using a loop — no recursion issues)
    countdown_loop!(3);

    // Nest tuples via recursion
    let t = nest_tuple!(1, 2, 3, 4);
    println!("Nested tuple: {:?}", t); // (1, (2, (3, 4)))

    // Peano numbers
    let zero = peano!(zero);
    let one = peano!(succ zero);
    let two = peano!(succ peano!(succ zero));
    println!("Peano zero: {:?}", zero);
    println!("Peano one: {:?}", one);
    println!("Peano two: {:?}", two);

    // CSV via recursion
    let s = csv_string!("apple", "banana", "cherry", "date");
    println!("CSV string: {}", s);

    println!("\nRecursive macro strategy:");
    println!("1. Define a base case (no recursion)");
    println!("2. Define recursive case(s) that call the macro with smaller input");
    println!("3. For literal recursion, provide explicit base cases OR");
    println!("4. Generate a runtime recursive function from the macro");
    println!("5. Rust limits macro recursion depth — ~128 levels default");
    println!("6. Use #![recursion_limit = \"N\"] to increase the limit");
}
